name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, macOS and web.
repository: https://github.com/flutter/packages/tree/main/packages/video_player/video_player
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.10.0
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: video_player_android
      ios:
        default_package: video_player_avfoundation
      macos:
        default_package: video_player_avfoundation
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  video_player_android:
    git:
      url: https://github.com/saninthottungal/packages
      path: packages/video_player/video_player_android
      ref: 27a8dd94919b6278db2014baad9fb4d1e2780f6a
  video_player_avfoundation: ^2.7.0
  video_player_platform_interface:
    git:
      url: https://github.com/saninthottungal/packages
      path: packages/video_player/video_player_platform_interface
      ref: 27a8dd94919b6278db2014baad9fb4d1e2780f6a
  video_player_web: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any

topics:
  - video
  - video-player

dependency_overrides:
  video_player_platform_interface:
    git:
      url: https://github.com/saninthottungal/packages
      path: packages/video_player/video_player_platform_interface
      ref: 27a8dd94919b6278db2014baad9fb4d1e2780f6a

